# frozen_string_literal: true

require "rails_helper"
require "tabler_ui/docs/navigation"
require "tabler_ui/docs/editor"

# The design editor's three JSON endpoints (EditorController): GET
# /ui/editor/schema (palette + property-panel payload), and POST
# /ui/editor/preview (workspace -> rendered HTML + generated ERB). See
# spec/lib/tabler_ui/docs/editor_page_spec.rb for the page shell and the
# preview iframe this data ultimately feeds.
#
# Node/workspace builders below mirror
# spec/lib/tabler_ui/docs/editor/workspace_spec.rb's own helpers -- same
# Contract-shaped Hashes, kept minimal for each example's own point.
RSpec.describe "TablerUi::Docs design editor endpoints", type: :request do
  def fragment(id, children = [])
    { "kind" => "fragment", "id" => id, "children" => children }
  end

  def heading(id, content = "Hello", level = 1)
    { "kind" => "heading", "id" => id, "level" => level, "content" => content }
  end

  def component_node(name, id, options = {})
    { "kind" => "component", "id" => id, "name" => name, "options" => options }
  end

  def partial(id, path)
    { "kind" => "partial", "id" => id, "path" => path }
  end

  def workspace_payload(files:, open:)
    { "version" => TablerUi::Docs::Editor::Contract::VERSION, "files" => files, "directories" => [], "open" => open }
  end

  def preview_body(tree, path: "index.html.erb")
    { path: path, workspace: workspace_payload(files: { path => { "tree" => tree } }, open: path) }
  end

  describe "GET /ui/editor/schema" do
    it "returns parseable JSON describing all 35 components" do
      get "/ui/editor/schema"

      expect(response).to have_http_status(:ok)
      expect(response.content_type).to include("application/json")

      json = JSON.parse(response.body)
      expect(json["version"]).to eq(TablerUi::Docs::Editor::Contract::VERSION)
      expect(json["components"].keys).to match_array(TablerUi::Docs::Navigation.components)
      expect(json["components"].keys.size).to eq(35)
    end
  end

  describe "POST /ui/editor/preview" do
    it "renders a valid single-file workspace to html + erb" do
      tree = fragment("root", [heading("h1", "Hello editor")])

      post "/ui/editor/preview", params: preview_body(tree), as: :json

      expect(response).to have_http_status(:ok)
      json = JSON.parse(response.body)

      expect(json["html"]).to include("Hello editor")
      expect(json["erb"]).to include("Generated by the tabler_ui design editor")
      expect(json["errors"]).to eq([])
      expect(json["workspace"]["open"]).to eq("index.html.erb")
    end

    # Regression, found live in the showcase rather than here. #preview
    # responds as JSON, so its lookup context defaults to formats: [:json],
    # and every component in this gem renders from a `_component.html.erb`
    # partial -- so every component came back as a "Missing partial" error
    # marker while the endpoint still returned 200 with a populated `html`
    # field. The happy-path example above could not catch it: a `heading`
    # node renders through `content_tag` and resolves no partial at all.
    # Assert real component markup, not merely that `html` is non-empty.
    it "renders real component markup, not a missing-partial marker" do
      tree = fragment("root", [component_node("button", "c1", "text" => "Save")])

      post "/ui/editor/preview", params: preview_body(tree), as: :json

      json = JSON.parse(response.body)
      expect(json["html"]).to include("btn")
      expect(json["html"]).to include("Save")
      expect(json["html"]).not_to include("Missing partial")
      expect(json["html"]).not_to include("alert-danger")
    end

    it "drops a non-allowlisted component name, reports it, and still renders the rest" do
      tree = fragment("root", [heading("h1", "Still here"), component_node("evil_component", "c1")])

      post "/ui/editor/preview", params: preview_body(tree), as: :json

      expect(response).to have_http_status(:ok)
      json = JSON.parse(response.body)

      expect(json["errors"].join).to match(/unknown or invalid component name/i)
      expect(json["html"]).to include("Still here")
      expect(json["html"]).not_to include("evil_component")
    end

    it "handles a cyclic partial-reference workspace by rendering an unresolved-partial marker" do
      files = {
        "a.html.erb" => { "tree" => fragment("fa", [partial("pa", "b.html.erb")]) },
        "b.html.erb" => { "tree" => fragment("fb", [partial("pb", "a.html.erb")]) }
      }
      body = { path: "a.html.erb", workspace: workspace_payload(files: files, open: "a.html.erb") }

      post "/ui/editor/preview", params: body, as: :json

      expect(response).to have_http_status(:ok)
      json = JSON.parse(response.body)

      expect(json["errors"].join).to match(/cycle detected: a\.html\.erb -> b\.html\.erb -> a\.html\.erb/)
      expect(json["html"]).to include("unresolved partial")
    end

    it "rejects a fatal workspace (bad version) with a 422 and no html/erb" do
      body = { path: "index.html.erb",
               workspace: { "version" => 999, "files" => {}, "directories" => [], "open" => nil } }

      post "/ui/editor/preview", params: body, as: :json

      expect(response).to have_http_status(:unprocessable_entity)
      json = JSON.parse(response.body)

      expect(json["errors"]).not_to be_empty
      expect(json).not_to have_key("html")
    end

    it "rejects a path that names no file in the resulting workspace" do
      tree = fragment("root", [heading("h1")])
      body = { path: "missing.html.erb",
               workspace: workspace_payload(files: { "index.html.erb" => { "tree" => tree } }, open: "index.html.erb") }

      post "/ui/editor/preview", params: body, as: :json

      expect(response).to have_http_status(:unprocessable_entity)
      json = JSON.parse(response.body)
      expect(json["errors"].join).to match(/does not name a file/)
    end

    it "rejects an oversized body before ever parsing it as JSON" do
      limit = TablerUi::Docs::Editor::Contract::LIMITS.fetch(:bytes)
      tree = fragment("root", [heading("h1", "x" * (limit + 1))])

      post "/ui/editor/preview", params: preview_body(tree), as: :json

      expect(response).to have_http_status(:unprocessable_entity)
      json = JSON.parse(response.body)
      expect(json["errors"].join).to match(/exceeds the #{limit}-byte limit/)
    end

    it "rejects a non-JSON-object body" do
      post "/ui/editor/preview", params: "[1, 2, 3]", headers: { "CONTENT_TYPE" => "application/json" }

      expect(response).to have_http_status(:unprocessable_entity)
      json = JSON.parse(response.body)
      expect(json["errors"].join).to match(/must be a JSON object/)
    end

    # CSRF: EditorController never calls skip_forgery_protection, so the
    # default `protect_from_forgery with: :exception` strategy applies to
    # this action exactly as it would to any other host-app POST. The
    # Combustion test env leaves forgery protection off (see rails_helper.rb
    # -- nothing turns it on), so every other example in this file passes
    # with no token at all, and would keep passing even if the controller
    # had no CSRF handling whatsoever -- flipping it on here for real is
    # what makes this suite capable of catching that regression.
    describe "CSRF protection" do
      around do |example|
        original = ActionController::Base.allow_forgery_protection
        ActionController::Base.allow_forgery_protection = true
        begin
          example.run
        ensure
          ActionController::Base.allow_forgery_protection = original
        end
      end

      def valid_body
        preview_body(fragment("root", [heading("h1", "Hi")]))
      end

      it "rejects the POST with no CSRF token, as JSON, not Rails' default HTML error page" do
        post "/ui/editor/preview", params: valid_body, as: :json

        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to include("application/json")
        expect(JSON.parse(response.body)["errors"].join).to match(/csrf/i)
      end

      it "accepts the POST when the show page's own token is sent back as a header" do
        get "/ui/editor"
        token = Nokogiri::HTML5.fragment(response.body)
                               .at_css("#tabler-ui-docs-editor")["data-tabler-ui--docs-editor-csrf-token-value"]

        expect(token).to be_present

        post "/ui/editor/preview", params: valid_body, as: :json, headers: { "X-CSRF-Token" => token }

        expect(response).to have_http_status(:ok)
      end
    end
  end
end
